package alafonin4.mafia.game.domain;

public enum RoleVariant {
    DEFAULT,
    PROSTITUTE_BLOCK_NIGHT,
    PROSTITUTE_MUTE_AND_VOTE_SHIELD,
    JOURNALIST_ROLE_REVEAL,
    JOURNALIST_VISITOR_REPORT,
    MANIAC_NEUTRAL,
    MANIAC_MAFIA
}
