import * as SecureStore from 'expo-secure-store';
import type { ReactNode } from 'react';
import { createContext, useContext, useEffect, useMemo, useState } from 'react';

import { STORAGE_KEYS } from '@/constants/config';
import { useSession } from '@/utils/session';

export type UserLanguage = 'EN' | 'RU' | 'JA';

export type TranslationKey = string;

const translations: Record<UserLanguage, Record<TranslationKey, string>> = {
  EN: {
    'language.english': 'English',
    'language.russian': 'Russian',
    'language.japanese': 'Japanese',
    'nav.lobby': 'Private Lobby',
    'nav.game': 'Active Table',
    'nav.historyRecord': 'Archive Record',
    'nav.dossier': 'Dossier',
    'nav.club': 'Private Club',
    'nav.user': 'Guest Card',
    'nav.notifications': 'Message Desk',
    'tabs.salon': 'Salon',
    'tabs.circle': 'Circle',
    'tabs.tables': 'Tables',
    'tabs.archive': 'Archive',
    'tabs.profile': 'Profile',
    'tabs.roleGallery': 'Role Gallery',
    'tabs.clubs': 'Clubs',
    'profile.language': 'Interface language',
    'profile.languageHint': 'Language is saved to your account and follows you between devices.',
    'profile.studioEyebrow': 'Profile Studio',
    'profile.studioTitle': 'Refine your playing identity',
    'profile.studioCopy': 'Adjust your public card, choose the roles that fit your instincts, and let the dossier tell a sharper story.',
    'profile.save': 'Save profile',
    'profile.saving': 'Saving...',
    'profile.checkingNickname': 'Checking nickname...',
    'profile.memberProfile': 'Member profile',
    'profile.playingTaste': 'Playing taste',
    'profile.viewDossier': 'View dossier',
    'profile.editProfile': 'Edit profile',
    'profile.logOut': 'Log out',
    'profile.chooseGallery': 'Choose from gallery',
    'profile.removeAvatar': 'Remove avatar',
    'profile.nickname': 'Nickname',
    'profile.favoriteRoles': 'Favorite roles',
    'profile.dislikedRoles': 'Disliked roles',
    'profile.chooseRolesHint': 'Tap to choose up to 3 roles',
    'profile.roleLimitHint': 'You can choose up to 3 roles in each list.',
    'profile.currentNickname': 'This is your current nickname.',
    'profile.nicknameAvailable': 'Nickname is available.',
    'profile.nicknameInvalid': 'Nickname is invalid',
    'profile.nicknameVerifyFailed': 'Could not verify nickname availability. Try again.',
    'profile.loadFailed': 'Load failed',
    'profile.cannotLoad': 'Cannot load profile',
    'profile.invalidProfile': 'Invalid profile',
    'profile.checkForm': 'Check the form',
    'profile.nicknameCheck': 'Nickname check',
    'profile.nicknameCheckWait': 'Please wait until nickname availability is confirmed.',
    'profile.nicknameUnavailable': 'Nickname unavailable',
    'profile.saveFailed': 'Save failed',
    'profile.cannotSave': 'Cannot save profile',
    'profile.permissionRequired': 'Permission required',
    'profile.photoPermission': 'Allow access to your photo library to choose an avatar',
    'profile.imageError': 'Image error',
    'profile.cannotReadImage': 'Cannot read the selected image',
    'profile.cannotOpenGallery': 'Cannot open gallery',
    'game.finishedTitle': 'Game finished',
    'game.finishedHistory': 'Ceremony',
    'game.finishedGames': 'Games',
    'game.moderatorConsole': 'Moderator console',
    'game.activeTable': 'Active table',
    'game.phase': 'Phase',
    'game.night': 'Night',
    'game.day': 'Day',
    'game.modeModerator': 'Mode: Moderator',
    'game.stages': 'Stages',
    'game.dayStage': 'Day',
    'game.votingStage': 'Voting',
    'game.nightStage': 'Night',
    'game.players': 'Players',
    'game.yourRole': 'Your role',
    'game.reviewRoleCard': 'Review role card',
    'game.discussionQueue': 'Discussion queue',
    'game.discussionQueueCopy': 'Take a place in the discussion queue for the group talk after speeches.',
    'game.alreadyInQueue': 'Already in queue',
    'game.joinDiscussionQueue': 'Join discussion queue',
    'game.actions': 'Actions',
    'game.noActions': 'No actions available right now.',
    'game.target': 'Target',
    'game.skipTarget': 'Skip target',
    'game.voteTarget': 'Vote target',
    'game.voteRound': 'Vote round',
    'game.submitVote': 'Submit vote',
    'game.submitAction': 'Submit action',
    'game.moderatorTimer': 'Moderator timer',
    'game.speech': 'Speech',
    'game.noSpeaker': 'No speaker',
    'game.discussion': 'Discussion',
    'game.nextSpeaker': 'Next speaker',
    'game.startDiscussion': 'Start discussion',
    'game.restartSpeeches': 'Restart speeches',
    'game.pause': 'Pause',
    'game.start': 'Start',
    'game.resetTimer': 'Reset timer',
    'game.timeIsUp': 'Time is up.',
    'game.timerInactive': 'Timer is active during the day discussion stage.',
    'game.queueAfterSpeeches': 'Discussion after speeches',
    'game.queueEmptyLong': 'No one has taken the discussion queue. Discussion stays at 03:00.',
    'game.queuedForDiscussion': 'Queued for discussion',
    'game.queueEmpty': 'Queue is empty.',
    'game.playersAndRoles': 'Players and roles',
    'game.roleColorHint': 'Red cards are mafia roles. Green cards are everyone else.',
    'game.enterTable': 'Enter the table',
    'game.openFullGallery': 'Open full gallery',
    'game.roleHidden': 'Role hidden',
    'game.ready': 'ready',
    'game.alive': 'alive',
    'game.queued': 'queued',
    'game.round': 'Round',
    'game.noActiveVote': 'No active vote',
    'game.submitted': 'submitted',
    'game.winnerMeta': 'Winner',
    'game.phaseChangeFailed': 'Phase change failed',
    'game.cannotLoadRoom': 'Cannot load game room',
    'game.cannotChangePhase': 'Cannot change phase',
    'game.queueFailed': 'Queue failed',
    'game.cannotJoinQueue': 'Cannot join discussion queue',
    'game.actionFailed': 'Action failed',
    'game.cannotSubmitAction': 'Cannot submit action',
    'game.rolesUnavailable': 'Roles unavailable',
    'game.cannotLoadRoleGallery': 'Cannot load role gallery',
    'hostAssistant.title': 'Host Assistant',
    'hostAssistant.subtitle': 'A quiet checklist for keeping the table crisp.',
    'hostAssistant.readiness': 'Confirm readiness',
    'hostAssistant.phaseControl': 'Choose the correct phase',
    'hostAssistant.nightActions': 'Resolve night actions',
    'hostAssistant.voting': 'Close the vote cleanly',
    'hostAssistant.discussion': 'Manage the discussion pace',
    'hostAssistant.complete': 'Archive the evening',
    'hostAssistant.readinessDetail': 'Every guest should be seated and ready before the first role reveal.',
    'hostAssistant.phaseControlDetail': 'Move only when the table has heard the current ruling.',
    'hostAssistant.nightActionsDetail': 'Wait until all required actions are submitted before daybreak.',
    'hostAssistant.votingDetail': 'Check the active vote round before advancing to the night.',
    'hostAssistant.discussionDetail': 'Use the timer and queue to keep the room elegant and fair.',
    'hostAssistant.completeDetail': 'When the winner is declared, send everyone into the ceremony.',
    'ceremony.eyebrow': 'Aftergame Ceremony',
    'ceremony.title': 'The table remembers',
    'ceremony.winner': 'Winner',
    'ceremony.openArchive': 'Open archive record',
    'ceremony.backToGames': 'Back to games',
    'ceremony.awards': 'Editorial awards',
    'ceremony.survivors': 'Survivors',
    'ceremony.tableSummary': 'Table summary',
    'ceremony.players': 'Final cast',
    'ceremony.noAwards': 'Awards will appear after richer vote data is available.',
    'ceremony.loading': 'Preparing the ceremony...',
    'ceremony.cannotPrepare': 'Cannot prepare ceremony',
    'common.rating': 'Rating',
    'common.games': 'Games',
    'common.wins': 'Wins',
    'common.notSpecified': 'Not specified yet',
    'common.error': 'Error',
    'common.host': 'Host',
    'common.noSurvivors': 'No survivors.',
    'common.hidden': 'Hidden',
    'common.selectedPrefix': 'Selected',
  },
  RU: {
    'tabs.salon': 'Салон',
    'tabs.circle': 'Круг',
    'tabs.tables': 'Столы',
    'tabs.archive': 'Архив',
    'tabs.profile': 'Профиль',
    'tabs.roleGallery': 'Галерея ролей',
    'tabs.clubs': 'Клубы',
    'profile.chooseGallery': 'Выбрать из галереи',
    'profile.removeAvatar': 'Удалить аватар',
    'profile.nickname': 'Никнейм',
    'profile.favoriteRoles': 'Любимые роли',
    'profile.dislikedRoles': 'Нелюбимые роли',
    'profile.chooseRolesHint': 'Выбери до 3 ролей',
    'profile.roleLimitHint': 'В каждом списке можно выбрать до 3 ролей.',
    'profile.currentNickname': 'Это твой текущий никнейм.',
    'profile.nicknameAvailable': 'Никнейм свободен.',
    'profile.nicknameInvalid': 'Некорректный никнейм',
    'profile.nicknameVerifyFailed': 'Не удалось проверить никнейм. Попробуй ещё раз.',
    'profile.loadFailed': 'Не удалось загрузить',
    'profile.cannotLoad': 'Не удалось загрузить профиль',
    'profile.invalidProfile': 'Профиль заполнен некорректно',
    'profile.checkForm': 'Проверь форму',
    'profile.nicknameCheck': 'Проверка никнейма',
    'profile.nicknameCheckWait': 'Дождись завершения проверки никнейма.',
    'profile.nicknameUnavailable': 'Никнейм недоступен',
    'profile.saveFailed': 'Не удалось сохранить',
    'profile.cannotSave': 'Не удалось сохранить профиль',
    'profile.permissionRequired': 'Нужно разрешение',
    'profile.photoPermission': 'Разреши доступ к галерее, чтобы выбрать аватар',
    'profile.imageError': 'Ошибка изображения',
    'profile.cannotReadImage': 'Не удалось прочитать выбранное изображение',
    'profile.cannotOpenGallery': 'Не удалось открыть галерею',
    'game.players': 'Игроки',
    'game.yourRole': 'Твоя роль',
    'game.reviewRoleCard': 'Посмотреть карту роли',
    'game.discussionQueue': 'Очередь обсуждения',
    'game.discussionQueueCopy': 'Займи место в очереди для общего обсуждения после речей.',
    'game.alreadyInQueue': 'Уже в очереди',
    'game.joinDiscussionQueue': 'Встать в очередь',
    'game.actions': 'Действия',
    'game.noActions': 'Сейчас нет доступных действий.',
    'game.target': 'Цель',
    'game.skipTarget': 'Без цели',
    'game.voteTarget': 'Цель голосования',
    'game.voteRound': 'Раунд голосования',
    'game.submitVote': 'Отправить голос',
    'game.submitAction': 'Отправить действие',
    'game.moderatorTimer': 'Таймер ведущего',
    'game.speech': 'Речь',
    'game.noSpeaker': 'Нет спикера',
    'game.discussion': 'Обсуждение',
    'game.nextSpeaker': 'Следующий спикер',
    'game.startDiscussion': 'Начать обсуждение',
    'game.restartSpeeches': 'Начать речи заново',
    'game.pause': 'Пауза',
    'game.start': 'Старт',
    'game.resetTimer': 'Сбросить таймер',
    'game.timeIsUp': 'Время вышло.',
    'game.timerInactive': 'Таймер активен на этапе дневного обсуждения.',
    'game.queueAfterSpeeches': 'Обсуждение после речей',
    'game.queueEmptyLong': 'В очереди никого нет. Обсуждение остаётся 03:00.',
    'game.queuedForDiscussion': 'В очереди на обсуждение',
    'game.queueEmpty': 'Очередь пуста.',
    'game.playersAndRoles': 'Игроки и роли',
    'game.roleColorHint': 'Красные карточки - роли мафии. Зелёные - все остальные.',
    'game.enterTable': 'Вернуться за стол',
    'game.openFullGallery': 'Открыть галерею ролей',
    'game.roleHidden': 'Роль скрыта',
    'game.ready': 'готовы',
    'game.alive': 'живы',
    'game.queued': 'в очереди',
    'game.round': 'Раунд',
    'game.noActiveVote': 'Нет активного голосования',
    'game.submitted': 'отправлено',
    'game.winnerMeta': 'Победитель',
    'game.phaseChangeFailed': 'Не удалось сменить фазу',
    'game.cannotLoadRoom': 'Не удалось загрузить игровую комнату',
    'game.cannotChangePhase': 'Фазу нельзя изменить',
    'game.queueFailed': 'Не удалось обновить очередь',
    'game.cannotJoinQueue': 'Не удалось встать в очередь',
    'game.actionFailed': 'Действие не отправлено',
    'game.cannotSubmitAction': 'Не удалось отправить действие',
    'game.rolesUnavailable': 'Роли недоступны',
    'game.cannotLoadRoleGallery': 'Не удалось загрузить галерею ролей',
    'ceremony.cannotPrepare': 'Не удалось подготовить церемонию',
    'common.error': 'Ошибка',
    'common.host': 'Ведущий',
    'common.noSurvivors': 'Выживших нет.',
    'common.hidden': 'Скрыто',
    'common.selectedPrefix': 'Выбрано',
    'language.english': 'Английский',
    'language.russian': 'Русский',
    'language.japanese': 'Японский',
    'nav.lobby': 'Приватное лобби',
    'nav.game': 'Игровой стол',
    'nav.historyRecord': 'Архив партии',
    'nav.dossier': 'Досье',
    'nav.club': 'Приватный клуб',
    'nav.user': 'Карточка игрока',
    'nav.notifications': 'Сообщения',
    'profile.language': 'Язык интерфейса',
    'profile.languageHint': 'Язык сохраняется в аккаунте и переносится между устройствами.',
    'profile.studioEyebrow': 'Студия профиля',
    'profile.studioTitle': 'Настрой свой игровой образ',
    'profile.studioCopy': 'Обнови публичную карточку, выбери любимые роли и позволь досье рассказать историю точнее.',
    'profile.save': 'Сохранить профиль',
    'profile.saving': 'Сохраняем...',
    'profile.checkingNickname': 'Проверяем ник...',
    'profile.memberProfile': 'Профиль участника',
    'profile.playingTaste': 'Игровой вкус',
    'profile.viewDossier': 'Открыть досье',
    'profile.editProfile': 'Редактировать профиль',
    'profile.logOut': 'Выйти',
    'game.finishedTitle': 'Игра завершена',
    'game.finishedHistory': 'Церемония',
    'game.finishedGames': 'Игры',
    'game.moderatorConsole': 'Пульт ведущего',
    'game.activeTable': 'Активный стол',
    'game.phase': 'Фаза',
    'game.night': 'Ночь',
    'game.day': 'День',
    'game.modeModerator': 'Режим: ведущий',
    'game.stages': 'Этапы',
    'game.dayStage': 'День',
    'game.votingStage': 'Голосование',
    'game.nightStage': 'Ночь',
    'hostAssistant.title': 'Помощник ведущего',
    'hostAssistant.subtitle': 'Спокойный чеклист, чтобы стол шел четко и красиво.',
    'hostAssistant.readiness': 'Проверить готовность',
    'hostAssistant.phaseControl': 'Выбрать верную фазу',
    'hostAssistant.nightActions': 'Завершить ночные действия',
    'hostAssistant.voting': 'Закрыть голосование',
    'hostAssistant.discussion': 'Держать темп обсуждения',
    'hostAssistant.complete': 'Отправить вечер в архив',
    'hostAssistant.readinessDetail': 'Все гости должны быть за столом и готовы до раскрытия ролей.',
    'hostAssistant.phaseControlDetail': 'Переходи дальше только после того, как стол услышал решение.',
    'hostAssistant.nightActionsDetail': 'Дождись всех обязательных действий перед рассветом.',
    'hostAssistant.votingDetail': 'Проверь активный раунд голосования перед переходом в ночь.',
    'hostAssistant.discussionDetail': 'Таймер и очередь помогают вести разговор честно и элегантно.',
    'hostAssistant.completeDetail': 'После объявления победителя отправь игроков на церемонию.',
    'ceremony.eyebrow': 'Послеигровая церемония',
    'ceremony.title': 'Стол запомнит этот вечер',
    'ceremony.winner': 'Победитель',
    'ceremony.openArchive': 'Открыть архив',
    'ceremony.backToGames': 'К играм',
    'ceremony.awards': 'Номинации вечера',
    'ceremony.survivors': 'Выжившие',
    'ceremony.tableSummary': 'Итоги стола',
    'ceremony.players': 'Финальный состав',
    'ceremony.noAwards': 'Номинации появятся, когда будет больше данных голосования.',
    'ceremony.loading': 'Готовим церемонию...',
    'common.rating': 'Рейтинг',
    'common.games': 'Игры',
    'common.wins': 'Победы',
    'common.notSpecified': 'Пока не указано',
  },
  JA: {
    'tabs.salon': 'サロン',
    'tabs.circle': 'サークル',
    'tabs.tables': 'テーブル',
    'tabs.archive': 'アーカイブ',
    'tabs.profile': 'プロフィール',
    'tabs.roleGallery': '役職ギャラリー',
    'tabs.clubs': 'クラブ',
    'profile.chooseGallery': 'ギャラリーから選択',
    'profile.removeAvatar': 'アバターを削除',
    'profile.nickname': 'ニックネーム',
    'profile.favoriteRoles': '好きな役職',
    'profile.dislikedRoles': '苦手な役職',
    'profile.chooseRolesHint': '最大3つまで選択',
    'profile.roleLimitHint': '各リストで最大3つの役職を選べます。',
    'profile.currentNickname': 'これは現在のニックネームです。',
    'profile.nicknameAvailable': 'このニックネームは使用できます。',
    'profile.nicknameInvalid': 'ニックネームが正しくありません',
    'profile.nicknameVerifyFailed': 'ニックネームを確認できませんでした。もう一度お試しください。',
    'profile.loadFailed': '読み込みに失敗しました',
    'profile.cannotLoad': 'プロフィールを読み込めません',
    'profile.invalidProfile': 'プロフィールが正しくありません',
    'profile.checkForm': '入力内容を確認してください',
    'profile.nicknameCheck': 'ニックネーム確認',
    'profile.nicknameCheckWait': 'ニックネーム確認が終わるまでお待ちください。',
    'profile.nicknameUnavailable': 'ニックネームは使用できません',
    'profile.saveFailed': '保存に失敗しました',
    'profile.cannotSave': 'プロフィールを保存できません',
    'profile.permissionRequired': '権限が必要です',
    'profile.photoPermission': 'アバターを選ぶために写真ライブラリへのアクセスを許可してください',
    'profile.imageError': '画像エラー',
    'profile.cannotReadImage': '選択した画像を読み込めません',
    'profile.cannotOpenGallery': 'ギャラリーを開けません',
    'game.players': 'プレイヤー',
    'game.yourRole': 'あなたの役職',
    'game.reviewRoleCard': '役職カードを見る',
    'game.discussionQueue': '議論キュー',
    'game.discussionQueueCopy': 'スピーチ後の全体議論に参加する順番を取ります。',
    'game.alreadyInQueue': 'キュー参加済み',
    'game.joinDiscussionQueue': 'キューに参加',
    'game.actions': 'アクション',
    'game.noActions': '現在利用できるアクションはありません。',
    'game.target': '対象',
    'game.skipTarget': '対象なし',
    'game.voteTarget': '投票対象',
    'game.voteRound': '投票ラウンド',
    'game.submitVote': '投票する',
    'game.submitAction': 'アクションを送信',
    'game.moderatorTimer': '司会タイマー',
    'game.speech': 'スピーチ',
    'game.noSpeaker': '発言者なし',
    'game.discussion': '議論',
    'game.nextSpeaker': '次の発言者',
    'game.startDiscussion': '議論を開始',
    'game.restartSpeeches': 'スピーチをやり直す',
    'game.pause': '一時停止',
    'game.start': '開始',
    'game.resetTimer': 'タイマーをリセット',
    'game.timeIsUp': '時間です。',
    'game.timerInactive': 'タイマーは昼の議論フェーズで有効です。',
    'game.queueAfterSpeeches': 'スピーチ後の議論',
    'game.queueEmptyLong': '議論キューは空です。議論時間は03:00のままです。',
    'game.queuedForDiscussion': '議論待ち',
    'game.queueEmpty': 'キューは空です。',
    'game.playersAndRoles': 'プレイヤーと役職',
    'game.roleColorHint': '赤いカードはマフィア役職、緑のカードはその他です。',
    'game.enterTable': 'テーブルに戻る',
    'game.openFullGallery': '役職ギャラリーを開く',
    'game.roleHidden': '役職は非公開',
    'game.ready': '準備完了',
    'game.alive': '生存',
    'game.queued': '待機中',
    'game.round': 'ラウンド',
    'game.noActiveVote': '進行中の投票なし',
    'game.submitted': '送信済み',
    'game.winnerMeta': '勝者',
    'game.phaseChangeFailed': 'フェーズ変更に失敗しました',
    'game.cannotLoadRoom': 'ゲームルームを読み込めません',
    'game.cannotChangePhase': 'フェーズを変更できません',
    'game.queueFailed': 'キュー更新に失敗しました',
    'game.cannotJoinQueue': '議論キューに参加できません',
    'game.actionFailed': 'アクションに失敗しました',
    'game.cannotSubmitAction': 'アクションを送信できません',
    'game.rolesUnavailable': '役職を利用できません',
    'game.cannotLoadRoleGallery': '役職ギャラリーを読み込めません',
    'ceremony.cannotPrepare': 'セレモニーを準備できません',
    'common.error': 'エラー',
    'common.host': '司会',
    'common.noSurvivors': '生存者はいません。',
    'common.hidden': '非公開',
    'common.selectedPrefix': '選択中',
    'language.english': '英語',
    'language.russian': 'ロシア語',
    'language.japanese': '日本語',
    'nav.lobby': 'プライベートロビー',
    'nav.game': '進行中の卓',
    'nav.historyRecord': '記録',
    'nav.dossier': 'ドシエ',
    'nav.club': 'プライベートクラブ',
    'nav.user': 'プレイヤーカード',
    'nav.notifications': 'メッセージ',
    'profile.language': '表示言語',
    'profile.languageHint': '言語設定はアカウントに保存され、別の端末にも反映されます。',
    'profile.studioEyebrow': 'プロフィールスタジオ',
    'profile.studioTitle': 'あなたのプレイスタイルを整える',
    'profile.studioCopy': '公開カード、好みの役職、そしてドシエをより鮮やかに整えます。',
    'profile.save': 'プロフィールを保存',
    'profile.saving': '保存中...',
    'profile.checkingNickname': 'ニックネーム確認中...',
    'profile.memberProfile': 'メンバープロフィール',
    'profile.playingTaste': 'プレイの好み',
    'profile.viewDossier': 'ドシエを見る',
    'profile.editProfile': 'プロフィール編集',
    'profile.logOut': 'ログアウト',
    'game.finishedTitle': 'ゲーム終了',
    'game.finishedHistory': 'セレモニー',
    'game.finishedGames': 'ゲーム',
    'game.moderatorConsole': '司会コンソール',
    'game.activeTable': '進行中の卓',
    'game.phase': 'フェーズ',
    'game.night': '夜',
    'game.day': '昼',
    'game.modeModerator': 'モード: 司会',
    'game.stages': 'ステージ',
    'game.dayStage': '昼',
    'game.votingStage': '投票',
    'game.nightStage': '夜',
    'hostAssistant.title': '司会アシスタント',
    'hostAssistant.subtitle': '上質な進行のための静かなチェックリスト。',
    'hostAssistant.readiness': '準備を確認',
    'hostAssistant.phaseControl': '正しいフェーズを選ぶ',
    'hostAssistant.nightActions': '夜の行動を解決',
    'hostAssistant.voting': '投票をきれいに締める',
    'hostAssistant.discussion': '議論のテンポを保つ',
    'hostAssistant.complete': '夜会を記録へ',
    'hostAssistant.readinessDetail': '役職公開の前に全員が着席し準備できているか確認します。',
    'hostAssistant.phaseControlDetail': '卓全体が裁定を聞いてから次へ進みます。',
    'hostAssistant.nightActionsDetail': '夜明け前に必要な行動がすべて提出されるのを待ちます。',
    'hostAssistant.votingDetail': '夜へ進む前に現在の投票ラウンドを確認します。',
    'hostAssistant.discussionDetail': 'タイマーと発言順で、公平で美しい議論にします。',
    'hostAssistant.completeDetail': '勝者発表後、全員をセレモニーへ案内します。',
    'ceremony.eyebrow': 'アフターゲームセレモニー',
    'ceremony.title': 'この卓は記憶される',
    'ceremony.winner': '勝者',
    'ceremony.openArchive': '記録を開く',
    'ceremony.backToGames': 'ゲームへ戻る',
    'ceremony.awards': '今夜のアワード',
    'ceremony.survivors': '生存者',
    'ceremony.tableSummary': '卓のまとめ',
    'ceremony.players': '最終キャスト',
    'ceremony.noAwards': '投票データが増えるとアワードが表示されます。',
    'ceremony.loading': 'セレモニーを準備中...',
    'common.rating': 'レーティング',
    'common.games': 'ゲーム',
    'common.wins': '勝利',
    'common.notSpecified': '未設定',
  },
};

const extraTranslations: Record<UserLanguage, Record<TranslationKey, string>> = {
  EN: {
    'auth.invalidForm': 'Invalid form',
    'auth.loginFailed': 'Login failed',
    'auth.registrationFailed': 'Registration failed',
    'auth.membersEntry': 'Members Entry',
    'auth.appTitle': 'Mafia Club',
    'auth.loginSubtitle': "Return to the table, reopen your private archive, and step directly into tonight's room.",
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.confirmPassword': 'Confirm password',
    'auth.signingIn': 'Signing in...',
    'auth.enterClub': 'Enter the club',
    'auth.noAccount': 'No account yet? Request membership',
    'auth.membership': 'Membership',
    'auth.joinTitle': 'Join Mafia Club',
    'auth.registerSubtitle': 'Create your profile, shape your playing identity, and keep every finished table in your archive.',
    'auth.creating': 'Creating...',
    'auth.becomeMember': 'Become a member',
    'auth.alreadyInside': 'Already inside? Return to entry',
    'common.loadFailed': 'Load failed',
    'common.createFailed': 'Create failed',
    'common.joinFailed': 'Join failed',
    'common.inviteFailed': 'Invite failed',
    'common.invalidRoom': 'Invalid room',
    'common.close': 'Close',
    'common.done': 'Done',
    'common.open': 'Open',
    'common.select': 'Select',
    'common.owner': 'Owner',
    'common.member': 'Member',
    'common.guest': 'Guest',
    'common.guests': 'Guests',
    'common.days': 'Days',
    'common.nights': 'Nights',
    'common.players': 'Players',
    'common.active': 'Active',
    'common.closed': 'Closed',
    'common.invited': 'Invited',
    'common.ready': 'Ready',
    'common.waiting': 'Waiting',
    'common.inside': 'Inside',
    'common.sent': 'Sent',
    'common.winner': 'Winner',
    'common.won': 'Won',
    'common.lost': 'Lost',
    'common.rank': 'rank',
    'common.voteStatus': 'Status',
    'common.player': 'Player',
    'common.votes': 'votes',
    'common.winRate': 'Win rate',
    'common.hosted': 'Hosted',
    'common.table': 'table',
    'common.tables': 'tables',
    'common.members': 'members',
    'games.eyebrow': "Tonight's Room",
    'games.title': 'Choose how you enter the table',
    'games.copy': 'Host a curated evening with your own composition of roles, or step into a room by invitation and join the circle already gathered.',
    'games.hostTitle': 'Host a private table',
    'games.hostCopy': 'Define the room, choose the cast, and open a polished lobby for your guests.',
    'games.createTable': 'Create table',
    'games.inviteTitle': 'Enter by invitation',
    'games.inviteCopy': 'Join by room code, clipboard link, or QR invitation from another host.',
    'games.joinRoom': 'Join room',
    'games.clubsTitle': 'Private clubs',
    'games.clubsCopy': 'Keep separate circles under one account, gather members, and build a dedicated archive for each company.',
    'games.openClubs': 'Open clubs',
    'games.activeLobby': 'Active lobby',
    'games.activeGame': 'Active game',
    'games.activeCopy': 'You are still seated at this table. Return without losing the current session.',
    'games.returnToTable': 'Return to table',
    'games.castTitle': 'Study the cast',
    'games.castCopy': 'Open a looping role gallery with full-screen editorial cards before the table begins.',
    'games.openRoleGallery': 'Open role gallery',
    'history.eyebrow': 'Archive',
    'history.title': 'Your finished evenings',
    'history.copy': 'Revisit each table as a private record: who won, how the room unfolded, and which recaps deserve another look.',
    'history.rowMeta': 'Winner {winner} / {guests} guests / {days} days / {nights} nights',
    'history.emptyTitle': 'No finished tables yet',
    'history.emptyCopy': 'Once a room ends, it will appear here as part of your private archive.',
    'rating.eyebrow': 'Salon Ranking',
    'rating.title': 'Who holds the room',
    'rating.copy': 'Follow the broader club ranking or narrow the view to your own circle of approved players.',
    'rating.allMembers': 'All members',
    'rating.myCircle': 'My circle',
    'rating.yourStanding': 'Your standing',
    'rating.entryMeta': 'Rating {rating} / {games} games / {wins} wins',
    'clubs.eyebrow': 'Private Clubs',
    'clubs.title': 'Separate every circle, keep every archive',
    'clubs.copy': 'Build one club for each company you play with, keep the member list distinct, and let every community grow its own archive of nights.',
    'clubs.createTitle': 'Create a new club',
    'clubs.createCopy': 'Use one club per friend group, building, cohort, or recurring salon.',
    'clubs.name': 'Club name',
    'clubs.description': 'Description',
    'clubs.namePlaceholder': 'Dorm salon',
    'clubs.descriptionPlaceholder': 'A close circle for weekly tables in the dorm lounge.',
    'clubs.creating': 'Creating...',
    'clubs.create': 'Create club',
    'clubs.yourClubs': 'Your clubs',
    'clubs.yourClubsCopy': 'Open a club to view members, invite friends, inspect club-only archive, or host a table for that circle.',
    'clubs.noDescription': 'No description yet.',
    'clubs.empty': 'No clubs yet. Create the first one for your next company.',
    'clubs.nameRequired': 'Club name required',
    'clubs.nameRequiredCopy': 'Give the club a name before creating it.',
    'clubs.cannotLoad': 'Cannot load clubs',
    'clubs.cannotCreate': 'Cannot create club',
    'club.cannotLoad': 'Cannot load club',
    'club.cannotInvite': 'Cannot invite member',
    'club.defaultDescription': 'A private circle built for recurring tables and its own evolving archive.',
    'club.ownerMeta': 'You curate this club',
    'club.memberMeta': 'You belong to this club',
    'club.hostTable': 'Host table for this club',
    'club.membersTitle': 'Members',
    'club.inviteFriends': 'Invite approved friends',
    'club.inviting': 'Inviting...',
    'club.inviteToClub': 'Invite to club',
    'club.noFriends': 'Every approved friend is already in this club or waiting on an invitation.',
    'club.archive': 'Club archive',
    'club.noHistory': 'No finished tables yet. The first archived night will appear here.',
    'club.privateArchive': 'Private club archive',
    'friends.eyebrow': 'Private Circle',
    'friends.title': 'People around your table',
    'friends.copy': 'Search for players, manage invitations, and keep your trusted circle close for future rooms.',
    'friends.search': 'Search',
    'friends.findPlayer': 'Find a player',
    'friends.placeholder': 'Nickname or email',
    'friends.searchCircle': 'Search circle',
    'friends.add': 'Add',
    'friends.requests': 'Requests and members',
    'friends.friends': 'Friends',
    'friends.incoming': 'Incoming',
    'friends.outgoing': 'Outgoing',
    'friends.openCardHint': 'Open the card to view the full profile.',
    'friends.accept': 'Accept',
    'friends.decline': 'Decline',
    'friends.cancel': 'Cancel',
    'friends.empty': 'This section is empty for now.',
    'friends.you': 'You',
    'friends.friend': 'Friend',
    'friends.sent': 'Sent',
    'friends.cannotLoad': 'Cannot load friends',
    'friends.cannotSearch': 'Cannot search users',
    'friends.cannotSend': 'Cannot send request',
    'friends.cannotAccept': 'Cannot accept request',
    'friends.cannotReject': 'Cannot reject request',
    'friends.cannotCancel': 'Cannot cancel request',
    'roles.unavailable': 'Role gallery is temporarily unavailable.',
    'roles.eyebrow': 'Private Briefing',
    'roles.gallery': 'Role gallery',
    'roles.caption': 'Swipe right for the next role, swipe left for the previous one. The carousel loops endlessly.',
    'roles.nightFaction': 'Night faction',
    'roles.townFaction': 'Town faction',
    'roles.independentFaction': 'Independent faction',
    'createGame.eyebrow': 'Host a Table',
    'createGame.title': "Compose tonight's room",
    'createGame.copy': 'Shape the scale of the evening, curate the role balance, and open a lobby that already feels intentional before the first guest arrives.',
    'createGame.cannotLoadCatalog': 'Cannot load role catalog',
    'createGame.checkSettings': 'Check room settings',
    'createGame.createFailed': 'Cannot create room',
    'createGame.clubContext': 'Club context',
    'createGame.independentTable': 'Independent private table',
    'createGame.independentCopy': 'Create a room outside any club archive.',
    'createGame.roomSettings': 'Room settings',
    'createGame.roomName': 'Room name',
    'createGame.roomPlaceholder': 'Velvet Chamber',
    'createGame.playerCount': 'Player count',
    'createGame.mafiaLimit': 'Mafia limit',
    'createGame.mafiaChosen': 'Mafia chosen',
    'createGame.rolesTotal': 'Roles total',
    'createGame.remainingSeats': 'Remaining seats',
    'createGame.curateCast': 'Curate the cast',
    'createGame.selectMafia': 'Select mafia roles',
    'createGame.selectTown': 'Select town roles',
    'createGame.mafiaSelection': 'Mafia selection',
    'createGame.townSelection': 'Town selection',
    'createGame.openingRoom': 'Opening room...',
    'createGame.openTable': 'Open private table',
    'createGame.mafiaRoles': 'Mafia roles',
    'createGame.townRoles': 'Town roles',
    'join.invalidInvite': 'Invalid invite',
    'join.invalidInviteCopy': 'Clipboard does not contain a valid room QR/link.',
    'join.roomCodeRequired': 'Room code is required',
    'join.loginRequired': 'Login required',
    'join.loginRequiredCopy': 'Sign in to join the room from this invite.',
    'join.cannotJoin': 'Cannot join room',
    'join.cameraDenied': 'Camera denied',
    'join.cameraDeniedCopy': 'Allow camera access to scan room QR codes.',
    'join.eyebrow': 'Invitation Entry',
    'join.title': 'Enter a private room',
    'join.copy': 'Join by room code, pasted invite, or QR scan. If a host shared a link with you, the app will recognize it automatically.',
    'join.roomCode': 'Room code',
    'join.joining': 'Joining...',
    'join.pasteInvite': 'Paste invite',
    'join.scanQr': 'Scan QR invitation',
    'join.membershipRequired': 'Membership is required before you can enter a private table.',
    'join.openLogin': 'Open login',
    'join.openRegistration': 'Open registration',
    'join.scanInvitation': 'Scan invitation',
    'join.invalidQr': 'Invalid QR',
    'join.invalidQrCopy': 'This QR code does not contain a valid room invite.',
    'lobby.cannotLoadRoom': 'Cannot load room',
    'lobby.cannotLoadFriends': 'Cannot load friends',
    'lobby.eyebrow': 'Private Lobby',
    'lobby.roomId': 'Room ID',
    'lobby.seatsFilled': '{filled} of {total} seats filled',
    'lobby.copyRoomId': 'Copy room ID',
    'lobby.copyInvite': 'Copy invite link',
    'lobby.showQr': 'Show QR invitation',
    'lobby.inviteMembers': 'Invite members',
    'lobby.guestList': 'Guest list',
    'lobby.toggleReady': 'Toggle readiness',
    'lobby.beginGame': 'Begin the game',
    'lobby.roomInvitation': 'Room invitation',
    'lobby.qrCaption': 'Scan with the app or with the phone camera.',
    'lobby.inviteFromCircle': 'Invite from your circle',
    'lobby.invite': 'Invite',
    'lobby.noFriends': 'No approved friends yet.',
    'notifications.cannotLoad': 'Cannot load notifications',
    'notifications.cannotJoinGame': 'Cannot join this game',
    'notifications.cannotJoinClub': 'Cannot join this club',
    'notifications.eyebrow': 'Message Desk',
    'notifications.title': 'Invites and approvals',
    'notifications.copy': 'Every invitation, request, and room call is gathered here in one quiet feed.',
    'notifications.joinRoom': 'Join room',
    'notifications.joinClub': 'Join club',
    'notifications.expired': 'Invitation expired',
    'notifications.empty': 'No notices have arrived yet.',
    'user.invalidProfileId': 'Invalid profile id',
    'user.cannotLoad': 'Cannot load profile',
    'user.cannotUpdateRelation': 'Cannot update relation',
    'user.guestCard': 'Guest card',
    'user.openDossier': 'Open private dossier',
    'user.addToCircle': 'Add to circle',
    'user.acceptRequest': 'Accept request',
    'user.declineRequest': 'Decline request',
    'user.cancelRequest': 'Cancel request',
    'user.removeFromCircle': 'Remove from circle',
    'dossier.cannotLoad': 'Cannot load dossier',
    'dossier.private': 'Private dossier',
    'dossier.meta': 'Rating {rating} / Hosted {hosted} {tables}',
    'dossier.recentForm': 'Recent form',
    'dossier.currentStreak': 'Current streak',
    'dossier.noTrend': 'No decided trend',
    'dossier.clubNote': 'A note from the club',
    'dossier.clubNoteCopy': 'A fuller dossier unlocks after a few more completed tables. For now, the essentials are in place and the deeper reads will sharpen with more finished sessions.',
    'dossier.roleMastery': 'Role mastery',
    'dossier.appearances': '{count} appearances / {rate} win rate',
    'dossier.voting': 'Voting intelligence',
    'dossier.ballotsCast': 'Ballots cast',
    'dossier.votesReceived': 'Votes received',
    'dossier.executionPrecision': 'Execution precision',
    'dossier.mafiaCatchRate': 'Mafia catch rate',
    'dossier.tableStyle': 'Table style',
    'dossier.averageTable': 'Average table',
    'dossier.averageDays': 'Average days',
    'dossier.averageNights': 'Average nights',
    'dossier.regularCompany': 'Regular company',
    'dossier.sharedGames': '{count} shared finished games',
    'dossier.noCompany': "The room is still learning this player's preferred company.",
    'dossier.recentTables': 'Recent tables',
    'historyDetails.cannotLoad': 'Cannot load game details',
    'historyDetails.signatureRecap': 'Signature Recap',
    'historyDetails.awards': 'Editorial awards',
    'historyDetails.survivors': 'Survivors',
    'historyDetails.noSurvivors': 'Nobody reached the end of the table alive.',
    'historyDetails.tableSummary': 'Table summary',
    'historyDetails.votes': 'Votes',
    'historyDetails.noVotes': 'No saved vote history for this game.',
    'modal.chooseUpTo': 'Choose up to {count} roles',
    'modal.faction': 'Faction',
  },
  RU: {
    'auth.invalidForm': 'Некорректная форма',
    'auth.loginFailed': 'Не удалось войти',
    'auth.registrationFailed': 'Не удалось зарегистрироваться',
    'auth.membersEntry': 'Вход для участников',
    'auth.appTitle': 'Mafia Club',
    'auth.loginSubtitle': 'Вернись за стол, открой личный архив и сразу войди в сегодняшнюю комнату.',
    'auth.email': 'Email',
    'auth.password': 'Пароль',
    'auth.confirmPassword': 'Повторите пароль',
    'auth.signingIn': 'Входим...',
    'auth.enterClub': 'Войти в клуб',
    'auth.noAccount': 'Нет аккаунта? Запросить членство',
    'auth.membership': 'Членство',
    'auth.joinTitle': 'Вступить в Mafia Club',
    'auth.registerSubtitle': 'Создай профиль, настрой игровой образ и сохраняй каждую завершённую партию в архиве.',
    'auth.creating': 'Создаём...',
    'auth.becomeMember': 'Стать участником',
    'auth.alreadyInside': 'Уже внутри? Вернуться ко входу',
    'common.loadFailed': 'Не удалось загрузить',
    'common.createFailed': 'Не удалось создать',
    'common.joinFailed': 'Не удалось присоединиться',
    'common.inviteFailed': 'Не удалось пригласить',
    'common.invalidRoom': 'Некорректная комната',
    'common.close': 'Закрыть',
    'common.done': 'Готово',
    'common.open': 'Открыть',
    'common.select': 'Выбрать',
    'common.owner': 'Владелец',
    'common.member': 'Участник',
    'common.guest': 'Гость',
    'common.guests': 'Гости',
    'common.days': 'Дни',
    'common.nights': 'Ночи',
    'common.players': 'Игроки',
    'common.active': 'Активно',
    'common.closed': 'Закрыто',
    'common.invited': 'Приглашён',
    'common.ready': 'Готов',
    'common.waiting': 'Ожидает',
    'common.inside': 'Внутри',
    'common.sent': 'Отправлено',
    'common.winner': 'Победитель',
    'common.won': 'Победа',
    'common.lost': 'Поражение',
    'common.rank': 'место',
    'common.voteStatus': 'Статус',
    'common.player': 'Игрок',
    'common.votes': 'голоса',
    'common.winRate': 'Процент побед',
    'common.hosted': 'Проведено',
    'common.table': 'стол',
    'common.tables': 'столов',
    'common.members': 'участников',
    'games.eyebrow': 'Комната вечера',
    'games.title': 'Выбери способ попасть за стол',
    'games.copy': 'Проведи камерный вечер со своим набором ролей или войди по приглашению в уже собранный круг.',
    'games.hostTitle': 'Провести приватный стол',
    'games.hostCopy': 'Настрой комнату, выбери состав и открой аккуратное лобби для гостей.',
    'games.createTable': 'Создать стол',
    'games.inviteTitle': 'Войти по приглашению',
    'games.inviteCopy': 'Присоединяйся по коду комнаты, ссылке из буфера или QR-приглашению ведущего.',
    'games.joinRoom': 'Войти в комнату',
    'games.clubsTitle': 'Приватные клубы',
    'games.clubsCopy': 'Разделяй разные круги, собирай участников и веди отдельный архив для каждой компании.',
    'games.openClubs': 'Открыть клубы',
    'games.activeLobby': 'Активное лобби',
    'games.activeGame': 'Игра в процессе',
    'games.activeCopy': 'Ты всё ещё за этим столом. Вернись без потери текущей сессии.',
    'games.returnToTable': 'Вернуться за стол',
    'games.castTitle': 'Изучить роли',
    'games.castCopy': 'Открой галерею ролей с полноэкранными карточками перед началом стола.',
    'games.openRoleGallery': 'Открыть галерею ролей',
    'history.eyebrow': 'Архив',
    'history.title': 'Завершённые вечера',
    'history.copy': 'Возвращайся к каждому столу как к личной записи: кто победил, как развивалась игра и какие итоги стоит пересмотреть.',
    'history.rowMeta': 'Победитель {winner} / гостей: {guests} / дней: {days} / ночей: {nights}',
    'history.emptyTitle': 'Завершённых столов пока нет',
    'history.emptyCopy': 'Когда комната закончится, она появится здесь как часть личного архива.',
    'rating.eyebrow': 'Рейтинг салона',
    'rating.title': 'Кто держит комнату',
    'rating.copy': 'Смотри общий рейтинг клуба или сузь список до своего круга подтверждённых игроков.',
    'rating.allMembers': 'Все участники',
    'rating.myCircle': 'Мой круг',
    'rating.yourStanding': 'Твоя позиция',
    'rating.entryMeta': 'Рейтинг {rating} / игр: {games} / побед: {wins}',
    'clubs.eyebrow': 'Приватные клубы',
    'clubs.title': 'Разделяй круги, сохраняй архивы',
    'clubs.copy': 'Создай отдельный клуб для каждой компании, держи списки участников отдельно и позволь каждому сообществу вести собственную историю вечеров.',
    'clubs.createTitle': 'Создать новый клуб',
    'clubs.createCopy': 'Один клуб — одна компания, общежитие, поток или регулярный салон.',
    'clubs.name': 'Название клуба',
    'clubs.description': 'Описание',
    'clubs.namePlaceholder': 'Салон общежития',
    'clubs.descriptionPlaceholder': 'Близкий круг для еженедельных столов в лаунже.',
    'clubs.creating': 'Создаём...',
    'clubs.create': 'Создать клуб',
    'clubs.yourClubs': 'Твои клубы',
    'clubs.yourClubsCopy': 'Открой клуб, чтобы смотреть участников, звать друзей, изучать архив клуба или провести стол для этого круга.',
    'clubs.noDescription': 'Описание пока не добавлено.',
    'clubs.empty': 'Клубов пока нет. Создай первый для следующей компании.',
    'clubs.nameRequired': 'Нужно название клуба',
    'clubs.nameRequiredCopy': 'Укажи название клуба перед созданием.',
    'clubs.cannotLoad': 'Не удалось загрузить клубы',
    'clubs.cannotCreate': 'Не удалось создать клуб',
    'club.cannotLoad': 'Не удалось загрузить клуб',
    'club.cannotInvite': 'Не удалось пригласить участника',
    'club.defaultDescription': 'Приватный круг для регулярных столов и собственного развивающегося архива.',
    'club.ownerMeta': 'Ты курируешь этот клуб',
    'club.memberMeta': 'Ты состоишь в этом клубе',
    'club.hostTable': 'Провести стол для клуба',
    'club.membersTitle': 'Участники',
    'club.inviteFriends': 'Пригласить подтверждённых друзей',
    'club.inviting': 'Приглашаем...',
    'club.inviteToClub': 'Пригласить в клуб',
    'club.noFriends': 'Все подтверждённые друзья уже в клубе или ждут приглашения.',
    'club.archive': 'Архив клуба',
    'club.noHistory': 'Завершённых столов пока нет. Первая архивная ночь появится здесь.',
    'club.privateArchive': 'Приватный архив клуба',
    'friends.eyebrow': 'Приватный круг',
    'friends.title': 'Люди вокруг твоего стола',
    'friends.copy': 'Ищи игроков, управляй приглашениями и держи надёжный круг рядом для будущих комнат.',
    'friends.search': 'Поиск',
    'friends.findPlayer': 'Найти игрока',
    'friends.placeholder': 'Никнейм или email',
    'friends.searchCircle': 'Искать в круге',
    'friends.add': 'Добавить',
    'friends.requests': 'Запросы и участники',
    'friends.friends': 'Друзья',
    'friends.incoming': 'Входящие',
    'friends.outgoing': 'Исходящие',
    'friends.openCardHint': 'Открой карточку, чтобы посмотреть полный профиль.',
    'friends.accept': 'Принять',
    'friends.decline': 'Отклонить',
    'friends.cancel': 'Отменить',
    'friends.empty': 'В этом разделе пока пусто.',
    'friends.you': 'Ты',
    'friends.friend': 'Друг',
    'friends.sent': 'Отправлено',
    'friends.cannotLoad': 'Не удалось загрузить друзей',
    'friends.cannotSearch': 'Не удалось найти пользователей',
    'friends.cannotSend': 'Не удалось отправить запрос',
    'friends.cannotAccept': 'Не удалось принять запрос',
    'friends.cannotReject': 'Не удалось отклонить запрос',
    'friends.cannotCancel': 'Не удалось отменить запрос',
    'roles.unavailable': 'Галерея ролей временно недоступна.',
    'roles.eyebrow': 'Приватный брифинг',
    'roles.gallery': 'Галерея ролей',
    'roles.caption': 'Свайп вправо — следующая роль, влево — предыдущая. Карусель зациклена.',
    'roles.nightFaction': 'Ночная фракция',
    'roles.townFaction': 'Фракция города',
    'roles.independentFaction': 'Независимая фракция',
    'createGame.eyebrow': 'Провести стол',
    'createGame.title': 'Собери сегодняшнюю комнату',
    'createGame.copy': 'Задай масштаб вечера, настрой баланс ролей и открой лобби, которое выглядит продуманным ещё до первого гостя.',
    'createGame.cannotLoadCatalog': 'Не удалось загрузить каталог ролей',
    'createGame.checkSettings': 'Проверь настройки комнаты',
    'createGame.createFailed': 'Не удалось создать комнату',
    'createGame.clubContext': 'Контекст клуба',
    'createGame.independentTable': 'Независимый приватный стол',
    'createGame.independentCopy': 'Создать комнату вне клубного архива.',
    'createGame.roomSettings': 'Настройки комнаты',
    'createGame.roomName': 'Название комнаты',
    'createGame.roomPlaceholder': 'Бархатная комната',
    'createGame.playerCount': 'Количество игроков',
    'createGame.mafiaLimit': 'Лимит мафии',
    'createGame.mafiaChosen': 'Выбрано мафии',
    'createGame.rolesTotal': 'Всего ролей',
    'createGame.remainingSeats': 'Свободные места',
    'createGame.curateCast': 'Настроить состав',
    'createGame.selectMafia': 'Выбрать роли мафии',
    'createGame.selectTown': 'Выбрать роли города',
    'createGame.mafiaSelection': 'Выбор мафии',
    'createGame.townSelection': 'Выбор города',
    'createGame.openingRoom': 'Открываем комнату...',
    'createGame.openTable': 'Открыть приватный стол',
    'createGame.mafiaRoles': 'Роли мафии',
    'createGame.townRoles': 'Роли города',
    'join.invalidInvite': 'Некорректное приглашение',
    'join.invalidInviteCopy': 'В буфере нет корректного QR/ссылки комнаты.',
    'join.roomCodeRequired': 'Нужен код комнаты',
    'join.loginRequired': 'Нужно войти',
    'join.loginRequiredCopy': 'Войди, чтобы присоединиться к комнате по приглашению.',
    'join.cannotJoin': 'Не удалось войти в комнату',
    'join.cameraDenied': 'Камера недоступна',
    'join.cameraDeniedCopy': 'Разреши доступ к камере, чтобы сканировать QR-коды комнат.',
    'join.eyebrow': 'Вход по приглашению',
    'join.title': 'Войти в приватную комнату',
    'join.copy': 'Войди по коду комнаты, вставленной ссылке или QR-скану. Если ведущий поделился ссылкой, приложение распознает её автоматически.',
    'join.roomCode': 'Код комнаты',
    'join.joining': 'Входим...',
    'join.pasteInvite': 'Вставить приглашение',
    'join.scanQr': 'Сканировать QR',
    'join.membershipRequired': 'Перед входом за приватный стол нужно членство.',
    'join.openLogin': 'Открыть вход',
    'join.openRegistration': 'Открыть регистрацию',
    'join.scanInvitation': 'Сканировать приглашение',
    'join.invalidQr': 'Некорректный QR',
    'join.invalidQrCopy': 'Этот QR-код не содержит корректного приглашения в комнату.',
    'lobby.cannotLoadRoom': 'Не удалось загрузить комнату',
    'lobby.cannotLoadFriends': 'Не удалось загрузить друзей',
    'lobby.eyebrow': 'Приватное лобби',
    'lobby.roomId': 'ID комнаты',
    'lobby.seatsFilled': '{filled} из {total} мест занято',
    'lobby.copyRoomId': 'Скопировать ID комнаты',
    'lobby.copyInvite': 'Скопировать ссылку',
    'lobby.showQr': 'Показать QR',
    'lobby.inviteMembers': 'Пригласить участников',
    'lobby.guestList': 'Список гостей',
    'lobby.toggleReady': 'Переключить готовность',
    'lobby.beginGame': 'Начать игру',
    'lobby.roomInvitation': 'Приглашение в комнату',
    'lobby.qrCaption': 'Сканируй через приложение или камеру телефона.',
    'lobby.inviteFromCircle': 'Пригласить из своего круга',
    'lobby.invite': 'Пригласить',
    'lobby.noFriends': 'Подтверждённых друзей пока нет.',
    'notifications.cannotLoad': 'Не удалось загрузить уведомления',
    'notifications.cannotJoinGame': 'Не удалось войти в игру',
    'notifications.cannotJoinClub': 'Не удалось войти в клуб',
    'notifications.eyebrow': 'Стол сообщений',
    'notifications.title': 'Приглашения и подтверждения',
    'notifications.copy': 'Все приглашения, запросы и вызовы в комнаты собраны здесь в одной спокойной ленте.',
    'notifications.joinRoom': 'Войти в комнату',
    'notifications.joinClub': 'Войти в клуб',
    'notifications.expired': 'Приглашение истекло',
    'notifications.empty': 'Уведомлений пока нет.',
    'user.invalidProfileId': 'Некорректный ID профиля',
    'user.cannotLoad': 'Не удалось загрузить профиль',
    'user.cannotUpdateRelation': 'Не удалось обновить связь',
    'user.guestCard': 'Карточка гостя',
    'user.openDossier': 'Открыть личное досье',
    'user.addToCircle': 'Добавить в круг',
    'user.acceptRequest': 'Принять запрос',
    'user.declineRequest': 'Отклонить запрос',
    'user.cancelRequest': 'Отменить запрос',
    'user.removeFromCircle': 'Удалить из круга',
    'dossier.cannotLoad': 'Не удалось загрузить досье',
    'dossier.private': 'Личное досье',
    'dossier.meta': 'Рейтинг {rating} / проведено {hosted} {tables}',
    'dossier.recentForm': 'Последняя форма',
    'dossier.currentStreak': 'Текущая серия',
    'dossier.noTrend': 'Нет выраженного тренда',
    'dossier.clubNote': 'Заметка от клуба',
    'dossier.clubNoteCopy': 'Полное досье откроется после ещё нескольких завершённых столов. Пока основы уже на месте, а глубокие выводы станут точнее с новыми партиями.',
    'dossier.roleMastery': 'Мастерство ролей',
    'dossier.appearances': 'появлений: {count} / побед: {rate}',
    'dossier.voting': 'Голосовательный интеллект',
    'dossier.ballotsCast': 'Голосов отдано',
    'dossier.votesReceived': 'Голосов получено',
    'dossier.executionPrecision': 'Точность казней',
    'dossier.mafiaCatchRate': 'Пойманная мафия',
    'dossier.tableStyle': 'Стиль стола',
    'dossier.averageTable': 'Средний стол',
    'dossier.averageDays': 'Средние дни',
    'dossier.averageNights': 'Средние ночи',
    'dossier.regularCompany': 'Постоянная компания',
    'dossier.sharedGames': 'общих завершённых игр: {count}',
    'dossier.noCompany': 'Комната ещё изучает предпочитаемую компанию этого игрока.',
    'dossier.recentTables': 'Последние столы',
    'historyDetails.cannotLoad': 'Не удалось загрузить детали игры',
    'historyDetails.signatureRecap': 'Итоговая сводка',
    'historyDetails.awards': 'Номинации вечера',
    'historyDetails.survivors': 'Выжившие',
    'historyDetails.noSurvivors': 'До конца стола живым не дошёл никто.',
    'historyDetails.tableSummary': 'Итоги стола',
    'historyDetails.votes': 'Голоса',
    'historyDetails.noVotes': 'История голосований для этой игры не сохранена.',
    'modal.chooseUpTo': 'Выбери до {count} ролей',
    'modal.faction': 'Фракция',
  },
  JA: {},
};

type LocalizationContextValue = {
  language: UserLanguage;
  setLanguage: (nextLanguage: UserLanguage) => Promise<void>;
  t: (key: TranslationKey) => string;
};

const LocalizationContext = createContext<LocalizationContextValue | null>(null);

export function LocalizationProvider({ children }: { children: ReactNode }) {
  const { api, session } = useSession();
  const [language, setLanguageState] = useState<UserLanguage>('EN');

  useEffect(() => {
    async function loadStoredLanguage() {
      const stored = await SecureStore.getItemAsync(STORAGE_KEYS.language);
      if (isUserLanguage(stored)) {
        setLanguageState(stored);
      }
    }

    void loadStoredLanguage();
  }, []);

  useEffect(() => {
    if (!session.userId) {
      return;
    }

    let cancelled = false;
    async function loadAccountLanguage() {
      try {
        const profile = await api.getMe();
        if (!cancelled && isUserLanguage(profile.language)) {
          setLanguageState(profile.language);
          await SecureStore.setItemAsync(STORAGE_KEYS.language, profile.language);
        }
      } catch {
      }
    }

    void loadAccountLanguage();
    return () => {
      cancelled = true;
    };
  }, [api, session.userId]);

  const value = useMemo<LocalizationContextValue>(() => ({
    language,
    setLanguage: async (nextLanguage) => {
      setLanguageState(nextLanguage);
      await SecureStore.setItemAsync(STORAGE_KEYS.language, nextLanguage);
    },
    t: (key) => extraTranslations[language][key] ?? translations[language][key] ?? extraTranslations.EN[key] ?? translations.EN[key] ?? key,
  }), [language]);

  return <LocalizationContext.Provider value={value}>{children}</LocalizationContext.Provider>;
}

export function useLocalization() {
  const context = useContext(LocalizationContext);
  if (!context) {
    throw new Error('Localization context is unavailable');
  }
  return context;
}

export const LANGUAGE_OPTIONS: { value: UserLanguage; labelKey: TranslationKey }[] = [
  { value: 'EN', labelKey: 'language.english' },
  { value: 'RU', labelKey: 'language.russian' },
  { value: 'JA', labelKey: 'language.japanese' },
];

function isUserLanguage(value: unknown): value is UserLanguage {
  return value === 'EN' || value === 'RU' || value === 'JA';
}
